services:
  owaspwaf:
    image: owasp/modsecurity-crs:nginx-alpine
    restart: always
    ports:
      - '80:80'
    environment:
      SERVERNAME: laravel-app
      BACKEND: http://laravel-app
      PORT: "8080"
      TZ: "Asia/Bangkok"
      ERRORLOG: "/var/log/error.log"
      ACCESSLOG: "/var/log/access.log"
      MODSEC_AUDIT_LOG_FORMAT: Native
      MODSEC_AUDIT_LOG_TYPE: Serial
      MODSEC_AUDIT_LOG: "/var/log/modsec_audit.log"
      MODSEC_RESP_BODY_ACCESS: "On"
      MODSEC_RESP_BODY_MIMETYPE: "text/plain text/html text/xml application/json"
  
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-container
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Why477@phiwat
      MYSQL_DATABASE: hospital
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Why477@phiwat

volumes:
  mysql-data:
